[theme]
# Tema customizado para Dashboards de Qu.AI Analytics

base="light"

primaryColor="#2563EB" # Color de resalte de botones - Azul Oscuro

backgroundColor="#FFFFFF" # Color de fondo - Blanco

secondaryBackgroundColor="#f5f5f5"